export const shopCategories = [
	{
		id: 1,
		name: "Hoddies",
		image: "https://cdn.shopify.com/s/files/1/0293/9277/files/12-12-24_S7_21_GHMI798FLLFS_Sand_CZ_DJ_10-00-27_54070_CM.jpg?v=1734132649&width=1000&height=1500&crop=center",
	},
	{
		id: 2,
		name: "Shorts",
		image: "https://cdn.shopify.com/s/files/1/0293/9277/files/04-10-24_S7_51_ZDF01T420002_Olive_CZ_DJ_11-45-06_42206_TT.jpg?v=1712936977&width=1000&height=1500&crop=center",
	},
	{
		id: 3,
		name: "Shoes",
		image: "https://cdn.shopify.com/s/files/1/0293/9277/files/03-12-25_S15_31_LEONARDO2NM_Black_ZSR_CZ_10-58-04_2428_PXF.jpg?v=1741974385&width=1000&height=1500&crop=center",
	},
	{
		id: 4,
		name: "Bag",
		image: "https://cdn.shopify.com/s/files/1/0293/9277/files/09-26-25_SL2PM_2_FNMA0019_Navy_ZSR_JP_15-15-12_FLATLAY_0240_PXF.jpg?v=1759163252&width=1000&height=1500&crop=center",
	},
	{
		id: 5,
		name: "Accessories",
		image: "https://cdn.shopify.com/s/files/1/0293/9277/products/04-14-22Studio2_KJ_KP_15-44-44_114_301433_Blackcombo_0956_SG.jpg?v=1650305534&width=1000&height=1500&crop=center",
	},
];

export const products = [
	{
		id: "p_001",
		name: "Kingston Slim-Fit Shirt",
		brand: "ZARA",
		sku: "KS-2024-01",
		category: ["shirts", "men", "new arrivals", "trending"],
		tags: ["cotton", "slim-fit", "green", "summer"],
		price: 49.99,
		discountPrice: 39.99,
		currency: "USD",
		taxInfo: "included",
		shippingInfo: "Free shipping",
		stock: 12,
		minQuantity: 1,
		maxQuantity: 5,
		images: [
			"https://cdn.shopify.com/s/files/1/0293/9277/files/02-02-26_S8_2_FNMKV61039_Green_ZSR_AB_MA_09-35-06_54575_BH_SKS.jpg?v=1770315389&width=1000&height=1500&crop=center",
			"https://cdn.shopify.com/s/files/1/0293/9277/files/02-02-26_S8_2_FNMKV61039_Green_ZSR_AB_MA_09-35-06_54575_BH_SKS_2.jpg?v=1770315390&width=1000&height=1500&crop=center",
		],
		variants: [
			{
				size: "S",
				color: "Green",
				stock: 3,
				image: "https://cdn.shopify.com/s/files/1/0293/9277/files/KS_S_Green.jpg",
			},
			{
				size: "M",
				color: "Green",
				stock: 5,
				image: "https://cdn.shopify.com/s/files/1/0293/9277/files/KS_M_Green.jpg",
			},
			{
				size: "L",
				color: "Green",
				stock: 4,
				image: "https://cdn.shopify.com/s/files/1/0293/9277/files/KS_L_Green.jpg",
			},
		],
		shortDescription: "Slim-fit green shirt made with 100% cotton.",
		fullDescription:
			"Kingston slim-fit shirt crafted with high-quality cotton. Comfortable, breathable, and perfect for casual or semi-formal occasions. Care: Machine wash cold, tumble dry low. Fits true to size.",
		actions: { canAddToCart: true, canWishlist: true, canShare: true },
		rating: null,
		reviewCount: 0,
		reviews: [],
	},
	{
		id: "p_002",
		name: "Luxe Denim Jeans",
		brand: "Levi's",
		sku: "LD-2024-02",
		category: ["jeans", "men", "denim"],
		tags: ["denim", "slim-fit", "blue", "casual"],
		price: 79.99,
		discountPrice: 69.99,
		currency: "USD",
		taxInfo: "included",
		shippingInfo: "Free shipping",
		stock: 20,
		minQuantity: 1,
		maxQuantity: 3,
		images: [
			"https://example.com/images/denim_1.jpg",
			"https://example.com/images/denim_2.jpg",
		],
		variants: [
			{
				size: "30",
				color: "Blue",
				stock: 5,
				image: "https://example.com/images/denim_30.jpg",
			},
			{
				size: "32",
				color: "Blue",
				stock: 7,
				image: "https://example.com/images/denim_32.jpg",
			},
			{
				size: "34",
				color: "Blue",
				stock: 8,
				image: "https://example.com/images/denim_34.jpg",
			},
		],
		shortDescription: "Classic slim-fit denim jeans.",
		fullDescription:
			"Levi's slim-fit denim jeans with comfortable stretch. Ideal for casual wear or semi-formal outings. Care: Machine wash cold, do not bleach.",
		actions: { canAddToCart: true, canWishlist: true, canShare: true },
		rating: null,
		reviewCount: 0,
		reviews: [],
	},
	{
		id: "p_003",
		name: "Premium Leather Jacket",
		brand: "H&M",
		sku: "PLJ-2024-03",
		category: ["jackets", "men", "outerwear"],
		tags: ["leather", "black", "premium", "winter"],
		price: 199.99,
		discountPrice: 179.99,
		currency: "USD",
		taxInfo: "included",
		shippingInfo: "Free shipping",
		stock: 5,
		minQuantity: 1,
		maxQuantity: 2,
		images: [
			"https://example.com/images/jacket_1.jpg",
			"https://example.com/images/jacket_2.jpg",
		],
		variants: [
			{
				size: "M",
				color: "Black",
				stock: 2,
				image: "https://example.com/images/jacket_M.jpg",
			},
			{
				size: "L",
				color: "Black",
				stock: 3,
				image: "https://example.com/images/jacket_L.jpg",
			},
		],
		shortDescription: "Premium black leather jacket for men.",
		fullDescription:
			"H&M premium leather jacket, durable and stylish. Perfect for winter and casual outings. Care: Professional leather cleaning only.",
		actions: { canAddToCart: true, canWishlist: true, canShare: true },
		rating: null,
		reviewCount: 0,
		reviews: [],
	},
];
